name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: go test -v ./...

      - name: Get next version
        id: get_next_version
        uses: thenativeweb/get-next-version@2.0.0

      - name: Build with Version Number
        run: go build -ldflags "-X main.GitCommit=$(git describe --tags) -s -w" -v ./...

      - name: Create new release
        if: ${{ steps.get_next_version.outputs.hasNextVersion == 'true' }}
        run: |
          NEXT_VERSION=${{ steps.get_next_version.outputs.version }}
          git tag $NEXT_VERSION
          git push origin $NEXT_VERSION